version: 0.2
phases:
  pre_build:
    commands:
      - echo checking docker version
      - docker --version
  build:
    commands:
      - echo Started building docker image `date`
      - docker build "./nitin.aspnetcore.northwind/" -o "./app/build/" 
artifacts:
  files:
    - ./app/build/*